#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
	    update-alternatives \
            --remove xinput-all_ALL \
            /etc/X11/xinit/xinput.d/maliit ;
	;;
    failed-upgrade)
	;;
    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
   ;;
esac

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/xdg/maliit.org/server.conf 0.99.0+git20130615+97e8335-0ubuntu2 -- "$@"
# End automatically added section

