#!/bin/sh -e

if [ "$1" = remove ]; then
    pam-auth-update --package --remove touch-extrausers
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init/ubuntu-touch-session-setup.conf -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init/ubuntu-touch-session.conf -- "$@"
# End automatically added section

